-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 14:47:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- --------------------------------------------\---------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecturers` (
  `idLecturers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NULL,
  `FamilyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLecturers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `primaryMail` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  `subjectCode` VARCHAR(100) NULL,
  `subjectName` VARCHAR(200) NULL,
  `description` VARCHAR(1000) NULL,
  `durationMin` INT NULL,
  `durationSec` INT NULL,
  `warningMin` INT NULL,
  `warningSec` INT NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `studentNumber` VARCHAR(100) NULL,
  `emailAddress` VARCHAR(100) NULL,
  `idProject` INT NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `surName` VARCHAR(100) NULL,
  `middleName` VARCHAR(100) NULL,
  `groupNumber` INT NULL,
  `mark` DECIMAL(5,2) NULL,
  `if_send_mail` TINYINT(1) DEFAULT 0, 
  PRIMARY KEY (`idStudents`),
  INDEX `fk_Students_Project1_idx` (`idProject` ASC),
  CONSTRAINT `fk_Students_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecturers_has_Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecturers_has_Project` (
  `idLecturers` INT NOT NULL,
  `idProject` INT NOT NULL,
  `If_Primary` TINYINT(1) NULL,
  PRIMARY KEY (`idLecturers`, `idProject`),
  INDEX `fk_Lecturers_has_Project_Project1_idx` (`idProject` ASC),
  INDEX `fk_Lecturers_has_Project_Lecturers1_idx` (`idLecturers` ASC),
  CONSTRAINT `fk_Lecturers_has_Project_Lecturers1`
    FOREIGN KEY (`idLecturers`)
    REFERENCES `mydb`.`Lecturers` (`idLecturers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Lecturers_has_Project_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Criteria` (
  `idCriteria` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `idProject` INT NOT NULL,
  `weighting` INT NULL,
  `maxMark` INT NULL,
  `markIncrement` VARCHAR(45) NULL,
  `if_only_comment` TINYINT(1) NULL,
  INDEX `fk_Criteria_Project1_idx` (`idProject` ASC),
  PRIMARY KEY (`idCriteria`),
  CONSTRAINT `fk_Criteria_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SubSection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SubSection` (
  `idSubSection` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NULL,
  `idCriteria` INT NOT NULL,
  PRIMARY KEY (`idSubSection`),
  INDEX `fk_subSection_Criteria1_idx` (`idCriteria` ASC),
  CONSTRAINT `fk_subSection_Criteria1`
    FOREIGN KEY (`idCriteria`)
    REFERENCES `mydb`.`Criteria` (`idCriteria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShortText`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShortText` (
  `idShortText` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1000) NULL,
  `grade` INT NULL,
  `idSubSection` INT NOT NULL,
  PRIMARY KEY (`idShortText`),
  INDEX `fk_shortText_subSection1_idx` (`idSubSection` ASC),
  CONSTRAINT `fk_shortText_subSection1`
    FOREIGN KEY (`idSubSection`)
    REFERENCES `mydb`.`SubSection` (`idSubSection`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LongText`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LongText` (
  `idLongText` INT NOT NULL AUTO_INCREMENT,
  `context` VARCHAR(5000) NULL,
  `idShortText` INT NOT NULL,
  PRIMARY KEY (`idLongText`),
  INDEX `fk_longText_shortText1_idx` (`idShortText` ASC),
  CONSTRAINT `fk_longText_shortText1`
    FOREIGN KEY (`idShortText`)
    REFERENCES `mydb`.`ShortText` (`idShortText`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mark` (
  `idMark` INT NOT NULL AUTO_INCREMENT,
  `idStudents` INT NOT NULL,
  `idLecturers` INT NOT NULL,
  `CriteriaName` VARCHAR(100) NULL,
  `Mark` DECIMAL(5,2) NULL,
  `MaxMark` INT NULL,
  `if_only_comment` TINYINT(1) NULL,
  INDEX `fk_FeedBack_Students1_idx` (`idStudents` ASC),
  INDEX `fk_FeedBack_Lecturers1_idx` (`idLecturers` ASC) ,
  PRIMARY KEY (`idMark`),
  CONSTRAINT `fk_FeedBack_Students1`
    FOREIGN KEY (`idStudents`)
    REFERENCES `mydb`.`Students` (`idStudents`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FeedBack_Lecturers1`
    FOREIGN KEY (`idLecturers`)
    REFERENCES `mydb`.`Lecturers` (`idLecturers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecturers_comment_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecturers_comment_Students` (
  `idLecturers` INT NOT NULL,
  `idStudents` INT NOT NULL,
  `comment` VARCHAR(5000) NULL,
  `totalMark` DECIMAL(5,2) NULL,  
  PRIMARY KEY (`idLecturers`, `idStudents`),
  INDEX `fk_Lecturers_has_Students_Students1_idx` (`idStudents` ASC),
  INDEX `fk_Lecturers_has_Students_Lecturers1_idx` (`idLecturers` ASC),
  CONSTRAINT `fk_Lecturers_has_Students_Lecturers1`
    FOREIGN KEY (`idLecturers`)
    REFERENCES `mydb`.`Lecturers` (`idLecturers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Lecturers_has_Students_Students1`
    FOREIGN KEY (`idStudents`)
    REFERENCES `mydb`.`Students` (`idStudents`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CriteriaComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CriteriaComment` (
  `idCriteriaComment` INT NOT NULL AUTO_INCREMENT,
  `idMark` INT NOT NULL,
  `subSection` VARCHAR(500) NULL,
  `shortText` VARCHAR(1000) NULL,
  `comment` VARCHAR(5000) NULL,
  PRIMARY KEY (`idCriteriaComment`),
  INDEX `fk_CriteriaComment_Mark1_idx` (`idMark` ASC),
  CONSTRAINT `fk_CriteriaComment_Mark1`
    FOREIGN KEY (`idMark`)
    REFERENCES `mydb`.`Mark` (`idMark`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

