-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 22:02:17 2019
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Marker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Marker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Marker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `middleName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `subjectName` VARCHAR(100) NOT NULL,
  `subjectCode` VARCHAR(10) NOT NULL,
  `durationSec` INT NOT NULL,
  `warningSec` INT NOT NULL,
  `description` TEXT NULL,
  `idPrincipal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Project_Marker1_idx` (`idPrincipal` ASC),
  CONSTRAINT `fk_Project_Marker1`
    FOREIGN KEY (`idPrincipal`)
    REFERENCES `mydb`.`Marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `middleName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `studentNumber` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Criterion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Criterion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Criterion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `idAuthor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Criterion_Marker1_idx` (`idAuthor` ASC),
  CONSTRAINT `fk_Criterion_Marker1`
    FOREIGN KEY (`idAuthor`)
    REFERENCES `mydb`.`Marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Field` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Field` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `idCriterion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Field_Criteria1_idx` (`idCriterion` ASC),
  CONSTRAINT `fk_Field_Criteria1`
    FOREIGN KEY (`idCriterion`)
    REFERENCES `mydb`.`Criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NOT NULL,
  `idField` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Field1_idx` (`idField` ASC),
  CONSTRAINT `fk_Comment_Field1`
    FOREIGN KEY (`idField`)
    REFERENCES `mydb`.`Field` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExpandedComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExpandedComment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ExpandedComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idComment` INT NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetailedComment_Comment_idx` (`idComment` ASC),
  CONSTRAINT `fk_DetailedComment_Comment`
    FOREIGN KEY (`idComment`)
    REFERENCES `mydb`.`Comment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectCriterion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProjectCriterion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProjectCriterion` (
  `idProject` INT NOT NULL,
  `idCriterion` INT NOT NULL,
  `weight` DOUBLE(5,2) NOT NULL,
  `maximumMark` DOUBLE(5,2) NOT NULL,
  `markIncrement` DOUBLE(5,2) NOT NULL,
  INDEX `fk_ProjectCriteria_Project1_idx` (`idProject` ASC),
  INDEX `fk_ProjectCriteria_Criteria1_idx` (`idCriterion` ASC),
  PRIMARY KEY (`idProject`, `idCriterion`),
  CONSTRAINT `fk_ProjectCriteria_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProjectCriteria_Criteria1`
    FOREIGN KEY (`idCriterion`)
    REFERENCES `mydb`.`Criterion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assessment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assessment` (
  `idProject` INT NOT NULL,
  `idCriterion` INT NOT NULL,
  `idStudent` INT NOT NULL,
  `idMarker` INT NOT NULL,
  `score` DOUBLE(5,2) NOT NULL,
  INDEX `fk_Assessment_ProjectSetCriteria1_idx` (`idProject` ASC, `idCriterion` ASC),
  INDEX `fk_Assessment_Student1_idx` (`idStudent` ASC),
  INDEX `fk_Assessment_Marker1_idx` (`idMarker` ASC),
  PRIMARY KEY (`idProject`, `idCriterion`, `idStudent`, `idMarker`),
  CONSTRAINT `fk_Assessment_ProjectSetCriteria1`
    FOREIGN KEY (`idProject` , `idCriterion`)
    REFERENCES `mydb`.`ProjectCriterion` (`idProject` , `idCriterion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Assessment_Student1`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Assessment_Marker1`
    FOREIGN KEY (`idMarker`)
    REFERENCES `mydb`.`Marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SelectedComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SelectedComment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SelectedComment` (
  `idProject` INT NOT NULL,
  `idCriterion` INT NOT NULL,
  `idStudent` INT NOT NULL,
  `idMarker` INT NOT NULL,
  `idField` INT NOT NULL,
  `idExpandedComment` INT NOT NULL,
  INDEX `fk_SelectedComment_Assessment1_idx` (`idProject` ASC, `idCriterion` ASC, `idStudent` ASC, `idMarker` ASC),
  PRIMARY KEY (`idProject`, `idCriterion`, `idStudent`, `idMarker`, `idField`),
  INDEX `fk_SelectedComment_Field1_idx` (`idField` ASC),
  INDEX `fk_SelectedComment_ExpandedComment1_idx` (`idExpandedComment` ASC),
  CONSTRAINT `fk_SelectedComment_Assessment1`
    FOREIGN KEY (`idProject` , `idCriterion` , `idStudent` , `idMarker`)
    REFERENCES `mydb`.`Assessment` (`idProject` , `idCriterion` , `idStudent` , `idMarker`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SelectedComment_Field1`
    FOREIGN KEY (`idField`)
    REFERENCES `mydb`.`Field` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SelectedComment_ExpandedComment1`
    FOREIGN KEY (`idExpandedComment`)
    REFERENCES `mydb`.`ExpandedComment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Audio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Audio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentInProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentInProject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentInProject` (
  `idProject` INT NOT NULL,
  `idStudent` INT NOT NULL,
  `group` INT NULL,
  `finalScore` DOUBLE(5,2) NULL,
  `finalRemark` TEXT NULL,
  `ifEmailed` TINYINT NOT NULL,
  `idAudio` INT NULL,
  INDEX `fk_ProjectTakeStudent_Project1_idx` (`idProject` ASC),
  INDEX `fk_ProjectTakeStudent_Student2_idx` (`idStudent` ASC),
  PRIMARY KEY (`idProject`, `idStudent`),
  INDEX `fk_StudentInProject_Audio1_idx` (`idAudio` ASC),
  CONSTRAINT `fk_ProjectTakeStudent_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ProjectTakeStudent_Student2`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_StudentInProject_Audio1`
    FOREIGN KEY (`idAudio`)
    REFERENCES `mydb`.`Audio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Remark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Remark` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Remark` (
  `idProject` INT NOT NULL,
  `idStudent` INT NOT NULL,
  `idMarker` INT NOT NULL,
  `text` TEXT NULL,
  INDEX `fk_Feedback_ProjectTakeStudent1_idx` (`idProject` ASC, `idStudent` ASC),
  INDEX `fk_Feedback_Marker2_idx` (`idMarker` ASC),
  PRIMARY KEY (`idProject`, `idStudent`, `idMarker`),
  CONSTRAINT `fk_Feedback_ProjectTakeStudent1`
    FOREIGN KEY (`idProject` , `idStudent`)
    REFERENCES `mydb`.`StudentInProject` (`idProject` , `idStudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Feedback_Marker2`
    FOREIGN KEY (`idMarker`)
    REFERENCES `mydb`.`Marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MarkerInProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MarkerInProject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MarkerInProject` (
  `idMarker` INT NOT NULL,
  `idProject` INT NOT NULL,
  INDEX `fk_MarkerInProject_Marker2_idx` (`idMarker` ASC),
  INDEX `fk_MarkerInProject_Project2_idx` (`idProject` ASC),
  PRIMARY KEY (`idMarker`, `idProject`),
  CONSTRAINT `fk_MarkerInProject_Marker2`
    FOREIGN KEY (`idMarker`)
    REFERENCES `mydb`.`Marker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MarkerInProject_Project2`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
